import type fr from "./fr"

type Translation = { [K in keyof typeof fr]: Record<string, unknown> }

const ar = {
  app: { name: "ريتيل أو إس المغرب", tagline: "الإدارة الكاملة لمتجرك" },
  common: {
    loading: "جارٍ التحميل…", save: "حفظ", saving: "جارٍ الحفظ…", cancel: "إلغاء", delete: "حذف", edit: "تعديل", add: "إضافة", create: "إنشاء", search: "بحث", searchPlaceholder: "بحث…", filter: "تصفية", export: "تصدير", import: "استيراد", confirm: "تأكيد", back: "رجوع", next: "التالي", previous: "السابق", submit: "إرسال", close: "إغلاق", yes: "نعم", no: "لا", all: "الكل", none: "لا شيء", actions: "إجراءات", details: "التفاصيل", total: "المجموع", subtotal: "المجموع دون ضريبة", tax: "الضريبة", discount: "خصم", quantity: "الكمية", price: "السعر", amount: "المبلغ", type: "النوع", unit: "الوحدة", date: "التاريخ", status: "الحالة", notes: "ملاحظات", description: "الوصف", name: "الاسم", email: "البريد الإلكتروني", phone: "الهاتف", address: "العنوان", city: "المدينة", store: "المتجر", allStores: "جميع المتاجر", active: "نشط", inactive: "غير نشط", reason: "السبب", optional: "اختياري", required: "هذا الحقل مطلوب", noResults: "لا توجد نتائج", showing: "{{from}}–{{to}} من {{total}}", page: "صفحة {{page}}", perPage: "في الصفحة", today: "اليوم", yesterday: "أمس", last7: "آخر 7 أيام", last30: "آخر 30 يوماً", thisMonth: "هذا الشهر", lastMonth: "الشهر الماضي", custom: "مخصص", from: "من", to: "إلى", apply: "تطبيق", vsPrevious: "مقارنة بالفترة السابقة", estimate: "تقدير", language: "اللغة", theme: "المظهر", light: "فاتح", dark: "داكن", system: "النظام", unknownError: "حدث خطأ. يرجى المحاولة مرة أخرى.", permissionDenied: "ليس لديك صلاحية لهذا الإجراء.", deleteConfirmTitle: "تأكيد الحذف", deleteConfirmText: "لا يمكن التراجع عن هذا الإجراء. هل تريد المتابعة؟", saved: "تم الحفظ بنجاح", deleted: "تم الحذف بنجاح", copied: "تم النسخ", print: "طباعة", download: "تحميل", refresh: "تحديث", viewAll: "عرض الكل", more: "المزيد", less: "أقل", select: "اختيار", change: "تغيير", remove: "إزالة", columns: "الأعمدة",
  },
  nav: { dashboard: "لوحة التحكم", pos: "نقطة البيع", products: "المنتجات", inventory: "المخزون", sales: "المبيعات", purchases: "المشتريات", suppliers: "الموردون", customers: "العملاء", expenses: "المصاريف", analytics: "التحليلات", ai: "المساعد الذكي", employees: "الموظفون", stores: "المتاجر", settings: "الإعدادات", register: "الصندوق", planner: "مخطط متجر جديد", notifications: "الإشعارات", audit: "سجل التدقيق", logout: "تسجيل الخروج", profile: "ملفي الشخصي" },
  auth: {
    signIn: "تسجيل الدخول", signUp: "إنشاء حساب", signOut: "تسجيل الخروج", email: "البريد الإلكتروني", password: "كلمة المرور", confirmPassword: "تأكيد كلمة المرور", newPassword: "كلمة المرور الجديدة", currentPassword: "كلمة المرور الحالية", firstName: "الاسم", lastName: "النسب", forgotPassword: "نسيت كلمة المرور؟", resetPassword: "إعادة تعيين كلمة المرور", sendResetLink: "إرسال الرابط", resetSent: "إذا كان هناك حساب بهذا البريد، فقد تم إرسال رابط إعادة التعيين.", resetSentDev: "إرسال البريد غير مُفعّل. في وضع التطوير يظهر الرابط في وحدة تحكم الخادم.", resetDone: "تمت إعادة تعيين كلمة المرور. يمكنك تسجيل الدخول.", invalidToken: "هذا الرابط غير صالح أو منتهي الصلاحية.", noAccount: "ليس لديك حساب؟", haveAccount: "لديك حساب بالفعل؟", invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.", accountInactive: "هذا الحساب معطّل. تواصل مع المالك.", rateLimited: "محاولات كثيرة. حاول مجدداً بعد بضع دقائق.", passwordRules: "8 أحرف على الأقل، مع حرف ورقم.", passwordsMismatch: "كلمتا المرور غير متطابقتين.", welcomeBack: "مرحباً بعودتك", signInSubtitle: "سجّل الدخول إلى مساحة الإدارة", signUpSubtitle: "أنشئ حساب المالك — ستقوم بإعداد متجرك في الخطوة التالية.", emailExists: "يوجد حساب بهذا البريد الإلكتروني.", accountCreated: "تم إنشاء الحساب. جارٍ تسجيل الدخول…", changePassword: "تغيير كلمة المرور", passwordChanged: "تم تغيير كلمة المرور.",
  },
  onboarding: {
    title: "لنقم بإعداد متجرك", subtitle: "بعض المعلومات للبدء. يمكنك تغيير كل شيء لاحقاً.", step1: "متجرك", step2: "معلومات الاتصال", step3: "المتجر الأول", businessName: "اسم المتجر التجاري", businessType: "نوع النشاط", ownerName: "اسم المالك", taxRate: "الضريبة الافتراضية", currency: "العملة", storeName: "اسم المتجر", storeNameHint: "مثال: محل المعاريف، المتجر الرئيسي…", finish: "إنهاء الإعداد",
    types: { MINI_MARKET: "سوبرماركت صغير", GROCERY: "بقالة / مواد غذائية", CLOTHING: "ملابس", ELECTRONICS: "إلكترونيات", COSMETICS: "مستحضرات تجميل", RESTAURANT: "مطعم / سناك", COFFEE_SHOP: "مقهى", PHARMACY: "شبه صيدلية", OTHER: "أخرى" },
  },
  dashboard: { title: "لوحة التحكم", revenue: "المبيعات", grossProfit: "الربح الإجمالي", netProfit: "الربح الصافي", transactions: "المعاملات", aov: "متوسط السلة", expenses: "المصاريف", inventoryValue: "قيمة المخزون (التكلفة)", lowStock: "مخزون منخفض", outOfStock: "نفد", topProducts: "المنتجات الأكثر مبيعاً", salesTrend: "تطور المبيعات", paymentMethods: "طرق الدفع", recentSales: "آخر المبيعات", lowStockProducts: "منتجات تحتاج إعادة تموين", noLowStock: "لا توجد منتجات بمخزون منخفض", noSales: "لا توجد مبيعات في هذه الفترة", grossMargin: "هامش الربح الإجمالي", netMargin: "هامش الربح الصافي", cogs: "تكلفة البضاعة المباعة", refunds: "المرتجعات", profit: "الربح", openRegister: "فتح الصندوق", goToPos: "الذهاب إلى نقطة البيع", registerOpen: "الصندوق مفتوح", registerClosed: "الصندوق مغلق" },
  pos: {
    title: "نقطة البيع", scanOrSearch: "امسح الباركود أو ابحث…", cart: "السلة", emptyCart: "السلة فارغة", emptyCartHint: "امسح منتجاً أو استخدم البحث", customer: "العميل", walkIn: "عميل عابر", selectCustomer: "اختر عميلاً", hold: "تعليق", resume: "استئناف", heldCarts: "السلات المعلقة", noHeldCarts: "لا توجد سلات معلقة", clear: "إفراغ", pay: "الدفع", payment: "الدفع", paymentMethod: "طريقة الدفع", splitPayment: "دفع مقسّم", addPayment: "إضافة دفعة", received: "المستلَم", remaining: "المتبقي", change: "الباقي للعميل", complete: "تأكيد البيع", completing: "جارٍ التأكيد…", saleComplete: "تم تسجيل البيع", receipt: "الإيصال", printReceipt: "طباعة الإيصال", printThermal: "طابعة حرارية", newSale: "بيع جديد", orderDiscount: "خصم على الطلب", lineDiscount: "خصم على السطر", unitPrice: "سعر الوحدة", stock: "المخزون: {{count}}", insufficientStock: "مخزون غير كافٍ لـ {{name}} (المتاح: {{available}})", registerRequired: "افتح الصندوق لقبول الدفع نقداً", registerClosed: "لا يوجد صندوق مفتوح", openRegister: "فتح الصندوق", productNotFound: "لم يتم العثور على منتج لـ «{{term}}»",
    methods: { CASH: "نقداً", CARD: "بطاقة / TPE", BANK_TRANSFER: "تحويل بنكي", CHECK: "شيك", OTHER: "أخرى", CREDIT: "كريدي (دين)" },
    creditFor: "دين على {{name}}", creditDue: "المتبقي للدفع (دين)", creditNeedsCustomer: "اختر عميلاً للبيع بالدين", creditNoLimit: "{{name}} ليس لديه حد ائتمان (حدّده في ملفه)", creditNotAllowed: "غير مسموح لك بالبيع بالدين",
    reference: "المرجع (رقم المعاملة…)", cashier: "أمين الصندوق", thankYou: "شكراً لزيارتكم!", items: "{{count}} منتج", quickAmounts: "مبالغ سريعة", exact: "المبلغ بالضبط", categories: "الفئات", allCategories: "الكل", keyboardHint: "Enter: إضافة · F2: دفع · F4: تعليق",
  },
  register: {
    title: "الصندوق", open: "فتح الصندوق", close: "إغلاق الصندوق", openingBalance: "رصيد الافتتاح", registerName: "اسم الصندوق", openedBy: "فُتح بواسطة", openedAt: "فُتح في", closedAt: "أُغلق في", cashSales: "مبيعات نقدية", cashRefunds: "مرتجعات نقدية", deposits: "إيداعات", withdrawals: "سحوبات", customerPayments: "تسديدات العملاء (دين)", expected: "النقد المتوقع", actual: "النقد المعدود", difference: "الفرق", differenceReason: "سبب الفرق", differenceReasonRequired: "السبب مطلوب عند وجود فرق", deposit: "إيداع", withdrawal: "سحب", addTransaction: "حركة نقدية", transactions: "الحركات", noOpen: "لا يوجد صندوق مفتوح لهذا المتجر", history: "سجل الصناديق", summary: "ملخص الجلسة", salesCount: "عدد المبيعات", closeConfirm: "هل تريد فعلاً إغلاق الصندوق؟", closed: "تم إغلاق الصندوق", opened: "تم فتح الصندوق",
    status: { OPEN: "مفتوح", CLOSED: "مغلق" }, types: { SALE: "بيع", REFUND: "مرتجع", DEPOSIT: "إيداع", WITHDRAWAL: "سحب", ADJUSTMENT: "تسوية", CUSTOMER_PAYMENT: "تسديد عميل" },
  },
  products: {
    title: "المنتجات", add: "إضافة منتج", edit: "تعديل المنتج", sku: "رمز المنتج", barcode: "الباركود", category: "الفئة", brand: "العلامة التجارية", supplier: "المورد", purchasePrice: "سعر الشراء (دون ضريبة)", sellingPrice: "سعر البيع (مع الضريبة)", costPrice: "متوسط التكلفة", margin: "الهامش", stock: "المخزون", minStock: "الحد الأدنى", maxStock: "الحد الأقصى", unit: "الوحدة", taxRate: "الضريبة", image: "الصورة (رابط)", initialStock: "المخزون الأولي", lowStockOnly: "المخزون المنخفض فقط", bulkPrice: "تحديث الأسعار", bulkStock: "تحديث المخزون", importCsv: "استيراد CSV", exportCsv: "تصدير CSV", importHint: "الأعمدة: name, sku, barcode, category, brand, purchasePrice, sellingPrice, taxRate, stockQuantity, minimumStock, unit", importResult: "{{created}} أُنشئ، {{updated}} حُدّث، {{errors}} خطأ", downloadTemplate: "تحميل النموذج", selected: "{{count}} محدد",
    priceMode: { SET: "تعيين إلى", PERCENT: "تعديل بنسبة %", AMOUNT: "تعديل بمبلغ (درهم)" }, field: { sellingPrice: "سعر البيع", purchasePrice: "سعر الشراء" },
    deleteConfirm: "حذف هذا المنتج؟ سيتم أرشفته ولن يظهر في نقطة البيع.", duplicateBarcode: "هذا الباركود مستخدم بالفعل في هذا المتجر", duplicateSku: "هذا الرمز مستخدم بالفعل في هذا المتجر", categories: "الفئات", brands: "العلامات التجارية", manageCategories: "إدارة الفئات", newCategory: "فئة جديدة", newBrand: "علامة جديدة", parentCategory: "الفئة الأم", productsCount: "{{count}} منتج", noProducts: "لا توجد منتجات", noProductsHint: "أضف أول منتج أو استورد ملف CSV.", generateSku: "توليد",
  },
  inventory: {
    title: "المخزون", movements: "حركات المخزون", adjust: "تسوية المخزون", transfer: "نقل", summary: "ملخص", costValue: "القيمة (التكلفة)", retailValue: "القيمة (البيع)", totalUnits: "الوحدات في المخزون", type: "النوع", previous: "قبل", change: "التغيير", newQty: "بعد", user: "المستخدم", product: "المنتج", adjustType: "نوع التسوية", newQuantity: "الكمية الجديدة", qty: "الكمية", fromStore: "المتجر المصدر", toStore: "المتجر الوجهة", reorder: "توصيات إعادة الطلب", reorderHint: "تقديرات مبنية على سرعة البيع خلال آخر {{days}} يوماً. ليست توقعات مضمونة.", avgDaily: "مبيعات / يوم", daysLeft: "الأيام المتبقية", suggested: "الكمية المقترحة", estCost: "التكلفة التقديرية",
    urgency: { OUT: "نفد", CRITICAL: "حرج", LOW: "منخفض", OK: "جيد" }, createPo: "إنشاء أمر شراء",
    types: { SALE: "بيع", PURCHASE: "شراء", RETURN: "إرجاع", ADJUSTMENT: "تسوية", TRANSFER: "نقل", DAMAGE: "تلف", LOSS: "فقدان" }, noMovements: "لا توجد حركات", adjusted: "تمت تسوية المخزون", transferred: "تم النقل",
  },
  sales: {
    title: "المبيعات", number: "رقم البيع", items: "المنتجات", payment: "الدفع", cashier: "أمين الصندوق", refund: "استرجاع", cancel: "إلغاء البيع", refundTitle: "استرجاع", refundQty: "الكمية المسترجعة", refundAmount: "المبلغ المسترجع", restock: "إعادة إلى المخزون", refundMethod: "طريقة الاسترجاع", refunded: "تم الاسترجاع", cancelled: "تم إلغاء البيع", cancelReason: "سبب الإلغاء", cancelHint: "ممكن فقط ما دام صندوق البيع مفتوحاً. وإلا استخدم الاسترجاع.", refunds: "المرتجعات",
    status: { COMPLETED: "مكتمل", CANCELLED: "ملغى", REFUNDED: "مسترجع", PARTIALLY_REFUNDED: "مسترجع جزئياً", DRAFT: "مسودة" }, noSales: "لا توجد مبيعات", viewReceipt: "عرض الإيصال",
    paymentStatus: { PAID: "مدفوع", PENDING: "بالدين (غير مدفوع)", PARTIALLY_PAID: "مدفوع جزئياً", REFUNDED: "مسترجع" },
    refundCreditHint: "لا يزال {{amount}} درهم مستحقاً كدين على هذه العملية: اختر «كريدي» لإلغاء هذا الدين بدلاً من إرجاع المال.",
  },
  purchases: {
    title: "المشتريات", orders: "أوامر الشراء", create: "أمر جديد", edit: "تعديل الأمر", number: "رقم الأمر", supplier: "المورد", expected: "التسليم المتوقع", delivered: "تم التسليم في", receive: "استلام", receiveTitle: "استلام البضاعة", ordered: "مطلوب", received: "مستلَم", receiving: "للاستلام", receiveAll: "استلام الكل", updatePrice: "تحديث سعر شراء المنتجات", markOrdered: "تحديد كمطلوب", saveDraft: "حفظ كمسودة", cancelOrder: "إلغاء الأمر", addProduct: "إضافة منتج", unitPriceHT: "سعر الوحدة (دون ضريبة)",
    status: { DRAFT: "مسودة", ORDERED: "مطلوب", PARTIALLY_RECEIVED: "مستلَم جزئياً", RECEIVED: "مستلَم", CANCELLED: "ملغى" }, noOrders: "لا توجد أوامر", receivedOk: "تم تسجيل الاستلام وتحديث المخزون",
  },
  suppliers: { title: "الموردون", add: "إضافة مورد", edit: "تعديل المورد", taxNumber: "الرقم الضريبي (ICE)", creditLimit: "حد الائتمان", balance: "الرصيد المستحق", pay: "تسجيل دفعة", paid: "تم تسجيل الدفعة", performance: "الأداء", orderCount: "الأوامر", totalPurchases: "إجمالي المشتريات", avgDelivery: "متوسط التسليم (أيام)", onTime: "التسليم في الوقت", products: "المنتجات الموردة", history: "سجل الأوامر", noSuppliers: "لا يوجد موردون" },
  customers: {
    title: "العملاء", add: "إضافة عميل", edit: "تعديل العميل", loyalty: "نقاط الولاء", totalSpending: "إجمالي الإنفاق", balance: "الرصيد المستحق", orders: "الطلبات", avgOrder: "متوسط السلة", lastPurchase: "آخر شراء", history: "سجل المشتريات", noCustomers: "لا يوجد عملاء",
    credit: "الدين (الكارني)", creditLimit: "حد الائتمان", creditLimitHint: "اتركه فارغاً لمنع البيع بالدين لهذا العميل.", creditAvailable: "الائتمان المتاح", noCredit: "بدون ائتمان", owes: "مدين بـ", settled: "مسدَّد",
    recordPayment: "تسجيل تسديد", paymentRecorded: "تم تسجيل التسديد. الرصيد الجديد: {{balance}} درهم", paymentHistory: "التسديدات المستلمة", cashPaymentHint: "يُضاف التسديد النقدي إلى الصندوق المفتوح.", receivablesSummary: "{{count}} عميل/عملاء مدينون بمجموع {{total}} درهم",
  },
  expenses: {
    title: "المصاريف", add: "إضافة مصروف", edit: "تعديل المصروف", category: "الفئة", paymentMethod: "طريقة الدفع", totalPeriod: "المجموع للفترة", categories: "فئات المصاريف", newCategory: "فئة جديدة", cashHint: "تُخصم المصاريف النقدية من الصندوق المفتوح.", noExpenses: "لا توجد مصاريف",
    codes: { RENT: "الإيجار", ELECTRICITY: "الكهرباء", INTERNET: "الإنترنت", SALARIES: "الأجور", TRANSPORT: "النقل", MARKETING: "التسويق", MAINTENANCE: "الصيانة", SUPPLIES: "المستلزمات", OTHER: "أخرى" },
  },
  analytics: {
    title: "التحليلات", pnl: "حساب النتائج", sales: "المبيعات", inventory: "المخزون", customers: "العملاء", suppliers: "الموردون", payments: "المدفوعات", revenue: "المبيعات (مع الضريبة)", netRevenue: "المبيعات الصافية (دون ضريبة)", cogs: "تكلفة البضاعة المباعة", grossProfit: "الربح الإجمالي", grossMargin: "هامش الربح الإجمالي", totalExpenses: "إجمالي المصاريف", netProfit: "الربح الصافي", netMargin: "هامش الربح الصافي", tax: "الضريبة المحصّلة", refunds: "المرتجعات", groupBy: "تجميع حسب",
    groups: { day: "اليوم", hour: "الساعة", cashier: "أمين الصندوق", category: "الفئة", store: "المتجر" }, turnover: "دوران المخزون (سنوي)", turnoverHint: "تكلفة البضاعة المباعة ÷ قيمة المخزون النهائي، سنوياً. تقريب مبني على مخزون نهاية الفترة.", potentialProfit: "الربح المحتمل في المخزون", byCategory: "حسب الفئة", topCustomers: "أفضل العملاء", anonymous: "مبيعات بدون عميل", newCustomers: "عملاء جدد", share: "الحصة", count: "العدد", formulas: "الصيغ", formulaText: "الربح الإجمالي = المبيعات الصافية − تكلفة البضاعة · الربح الصافي = الربح الإجمالي − المصاريف · الهامش = الربح ÷ المبيعات الصافية",
    export: "تصدير", exportPdf: "تحميل PDF", exportCsv: "تحميل CSV (Excel)", exporting: "جارٍ الإنشاء…", salesReport: "تقرير المبيعات", inventoryReport: "تقرير المخزون", customerReport: "تقرير العملاء", topProducts: "أفضل المنتجات", paymentMethods: "طرق الدفع", receivables: "ديون العملاء (كريدي)", generatedAt: "أُنشئ في", page: "صفحة",
    revenueSection: "المبيعات", grossRevenue: "المبيعات الإجمالية (مع الضريبة)", taxCollected: "الضريبة المحصّلة", netRevenueHT: "المبيعات الصافية (بدون ضريبة)", expensesSection: "المصاريف", resultSection: "النتيجة", transactions: "المعاملات", averageOrder: "متوسط السلة",
    pnlNote: "تُحتسب المبيعات بالدين كإيراد في تاريخ البيع (المحاسبة على أساس الاستحقاق). أرصدة العملاء المستحقة مدرجة في تقرير ديون العملاء.",
    units: "الوحدات", stockValuation: "تقييم المخزون", productCount: "عدد المنتجات", totalUnits: "الوحدات في المخزون", costValue: "القيمة بسعر التكلفة", retailValue: "القيمة بسعر البيع", cogsInPeriod: "تكلفة البضاعة المباعة في الفترة", anonymousSales: "مبيعات بدون عميل محدد", debtors: "العملاء المدينون", totalReceivables: "مجموع الديون",
  },
  ai: {
    title: "المساعد الذكي", subtitle: "اسأل بالفرنسية أو العربية أو الدارجة أو الإنجليزية. الإجابات محسوبة من بياناتك الحقيقية.", placeholder: "مثال: شنو المنتج لي كيربحني أكثر هاد الشهر؟", ask: "اسأل", examples: "أمثلة", ex1: "شنو أكثر منتج تباع هاد السيمانة؟", ex2: "شنو المنتجات لي قريبة تنفد؟", ex3: "علاش نقصو الأرباح هاد الشهر؟", ex4: "شنو خاصني نشري من المورد؟", ex5: "ملخص المبيعات لهذا الشهر", ex6: "Quel produit me rapporte le plus ?",
    source: { llm: "إجابة مولّدة بالذكاء الاصطناعي من بياناتك", template: "إجابة محسوبة من بياناتك" }, llmNotConfigured: "لم يتم إعداد مفتاح API للذكاء الاصطناعي: الإجابات محسوبة بنماذج حتمية. أضف OPENAI_API_KEY للحصول على إجابات بلغة طبيعية.", llmDegraded: "خدمة الذكاء الاصطناعي مُهيّأة لكنها غير متاحة ({{reason}}): الإجابات محسوبة بنماذج حتمية من بياناتك.", period: "الفترة المحللة", showData: "عرض البيانات", thinking: "جارٍ التحليل…",
  },
  planner: {
    title: "مساعد المتجر الجديد", subtitle: "احصل على مقترح تخطيط من ميزانيتك. جميع القيم تقديرية.", budget: "الميزانية الإجمالية (درهم)", businessType: "نوع النشاط", size: "المساحة (م²)", customers: "العملاء المتوقعون / يوم", rent: "الإيجار الشهري (درهم، اختياري)", employees: "الموظفون", generate: "توليد المقترح", allocation: "توزيع الميزانية", equipment: "المعدات", essential: "أساسي", optional: "اختياري", categories: "الفئات والمخزون الأولي", recurring: "المصاريف الشهرية التقديرية", projection: "التوقعات", monthlyRevenue: "المبيعات الشهرية التقديرية", monthlyGross: "الربح الإجمالي الشهري", monthlyNet: "الربح الصافي الشهري", breakEven: "نقطة التعادل (مبيعات صافية / شهر)", breakEvenCustomers: "العملاء / يوم اللازمون", payback: "فترة استرداد الاستثمار", months: "{{count}} شهر", notProfitable: "غير مربح بهذه الفرضيات", assumptions: "الفرضيات", formulas: "الصيغ المستخدمة", disclaimer: "تعتمد هذه التقديرات على متوسطات ولا تضمن أي نتيجة مالية.", inventoryBudget: "ميزانية المخزون الأولي", workingCapital: "احتياطي نقدي", deposit: "الضمان (شهران)", firstRent: "الإيجار الأول",
  },
  notifications: { title: "الإشعارات", markAllRead: "تحديد الكل كمقروء", empty: "لا توجد إشعارات", unread: "{{count}} غير مقروء", types: { LOW_STOCK: "مخزون منخفض", OUT_OF_STOCK: "نفد المخزون", LARGE_EXPENSE: "مصروف كبير", SALES_DECREASE: "انخفاض المبيعات", REGISTER_DISCREPANCY: "فرق في الصندوق", PURCHASE_RECEIVED: "تم استلام الطلب", SYSTEM: "النظام" } },
  employees: {
    title: "الموظفون", add: "إضافة موظف", edit: "تعديل الموظف", role: "الدور", stores: "المتاجر", lastLogin: "آخر دخول", never: "أبداً", resetPassword: "كلمة مرور جديدة (اختياري)",
    roles: { OWNER: "المالك", ADMIN: "مدير النظام", MANAGER: "مسيّر", CASHIER: "أمين الصندوق", INVENTORY_MANAGER: "مسؤول المخزون", ACCOUNTANT: "محاسب" },
    roleHints: { OWNER: "وصول كامل بما في ذلك الفوترة والحذف.", ADMIN: "وصول تشغيلي كامل باستثناء الإعدادات الحرجة.", MANAGER: "المبيعات، المخزون، المشتريات، التقارير.", CASHIER: "المبيعات والصندوق فقط.", INVENTORY_MANAGER: "المنتجات، المخزون، المشتريات.", ACCOUNTANT: "التقارير، المصاريف، التدقيق (قراءة)." },
    statuses: { ACTIVE: "نشط", INACTIVE: "غير نشط", SUSPENDED: "موقوف" }, deleteConfirm: "حذف هذا الموظف؟ سيتم الاحتفاظ بسجله.",
  },
  stores: { title: "المتاجر", add: "إضافة متجر", edit: "تعديل المتجر", size: "المساحة (م²)", openTime: "الافتتاح", closeTime: "الإغلاق", products: "المنتجات", users: "المستخدمون", deleteHint: "لا يمكن حذف المتجر إلا إذا لم يبقَ فيه مخزون ولا صندوق مفتوح.", current: "المتجر الحالي" },
  settings: {
    title: "الإعدادات", business: "الشركة", profile: "الملف الشخصي", security: "الأمان", appearance: "المظهر", logo: "الشعار (رابط)", plan: "الاشتراك", audit: "سجل التدقيق", auditEmpty: "لا توجد إدخالات", action: "الإجراء", entity: "الكيان", when: "متى", who: "من", ip: "IP",
    integrations: "التكاملات", integrationsHint: "تُقرأ المفاتيح من متغيرات بيئة الخادم (.env). لا تُعرض أبداً ولا تُرسل إلى المتصفح.", configured: "مُهيّأ", notConfigured: "غير مُهيّأ", active: "نشط", fallback: "احتياطي في الذاكرة", database: "قاعدة البيانات",
    aiIntegration: "المساعد الذكي (OpenAI)", aiHelp: "عيّن OPENAI_API_KEY (و OPENAI_MODEL) للحصول على إجابات بلغة طبيعية. بدون مفتاح يجيب المساعد بنماذج حتمية.",
    emailIntegration: "البريد الإلكتروني (SMTP)", emailHelp: "عيّن SMTP_HOST و SMTP_PORT و SMTP_USER و SMTP_PASSWORD و SMTP_FROM لإعادة تعيين كلمة المرور والتنبيهات.",
    redisIntegration: "Redis (تحديد معدل مشترك)", redisHelp: "عيّن REDIS_URL لمشاركة تحديد المعدل بين عدة نسخ. بدون Redis يُستخدم محدد في الذاكرة.",
    cronIntegration: "المهمة اليومية (cron)", cronHelp: "استدعِ POST /api/cron/daily مع الترويسة Authorization: Bearer CRON_SECRET مرة يومياً.",
    whatsappIntegration: "واتساب", whatsappHelp: "غير مُنفَّذ. البنية جاهزة لمزوّد (مثل WhatsApp Business API).",
    sendTestEmail: "إرسال بريد تجريبي", testEmailSent: "تم إرسال بريد تجريبي إلى {{to}}", model: "النموذج", lastError: "آخر خطأ",
  },
  errors: { VALIDATION_ERROR: "بيانات غير صالحة", UNAUTHORIZED: "انتهت الجلسة، يرجى تسجيل الدخول مجدداً", FORBIDDEN: "إجراء غير مسموح", NOT_FOUND: "العنصر غير موجود", CONFLICT: "تعارض مع بيانات موجودة", INSUFFICIENT_STOCK: "مخزون غير كافٍ", REGISTER_CLOSED: "الصندوق مغلق", REGISTER_ALREADY_OPEN: "هناك صندوق مفتوح بالفعل", PAYMENT_MISMATCH: "المدفوعات لا تطابق المجموع", CREDIT_NOT_ALLOWED: "هذا العميل ليس لديه حد ائتمان. حدّد واحداً في ملفه أولاً.", CREDIT_LIMIT_EXCEEDED: "تم تجاوز حد الائتمان", REFUND_EXCEEDS_CREDIT: "المبلغ يتجاوز الدين المتبقي على هذه العملية", NO_OUTSTANDING_BALANCE: "هذا العميل ليس لديه رصيد مستحق", INVALID_STATE: "العملية غير ممكنة في الحالة الحالية", RATE_LIMITED: "طلبات كثيرة، يرجى الانتظار", INTERNAL_ERROR: "خطأ في الخادم، حاول مجدداً", NETWORK: "تعذر الاتصال. تحقق من الشبكة." },
  pwa: { install: "تثبيت التطبيق", offline: "أنت غير متصل. بعض الميزات غير متاحة." },
  offline: {
    title: "المبيعات دون اتصال", description: "تُحفظ المبيعات المسجّلة بدون اتصال على هذا الجهاز وتُرسل تلقائياً إلى الخادم عند عودة الشبكة. تبقى هنا أي عملية يرفضها الخادم حتى تصحيح السبب.",
    offline: "غير متصل", online: "متصل", queued: "{{count}} قيد الانتظار", empty: "لا توجد مبيعات معلّقة", status: { pending: "قيد الانتظار", failed: "مرفوضة" },
    retry: "إعادة المحاولة", discard: "حذف", discardTitle: "حذف عملية البيع دون اتصال؟", discardText: "ستُحذف العملية {{ref}} نهائياً من هذا الجهاز ولن تُرسل إلى الخادم أبداً. لن يُخصم المخزون.",
    syncNow: "مزامنة الآن", syncedCount: "تمت مزامنة {{count}} عملية", failedCount: "رفض الخادم {{count}} عملية",
    saleQueued: "دون اتصال: حُفظت العملية {{ref}} على هذا الجهاز وستُزامَن عند عودة الشبكة", provisionalReceipt: "إيصال مؤقت — دون اتصال",
    fixThenRetry: "صحّح السبب ثم أعد المحاولة", creditNotOffline: "المبيعات بالدين تحتاج اتصالاً (التحقق من الحد).", servedFromCache: "البيانات معروضة من الذاكرة المحلية", pendingBanner: "{{count}} عملية دون اتصال بانتظار المزامنة",
  },
} satisfies Translation

export default ar
