import type fr from "./fr"

type Translation = { [K in keyof typeof fr]: Record<string, unknown> }

const en = {
  app: { name: "RetailOS Morocco", tagline: "Complete management for your store" },
  common: {
    loading: "Loading…", save: "Save", saving: "Saving…", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add", create: "Create", search: "Search", searchPlaceholder: "Search…", filter: "Filter", export: "Export", import: "Import", confirm: "Confirm", back: "Back", next: "Next", previous: "Previous", submit: "Submit", close: "Close", yes: "Yes", no: "No", all: "All", none: "None", actions: "Actions", details: "Details", total: "Total", subtotal: "Subtotal (excl. tax)", tax: "VAT", discount: "Discount", quantity: "Quantity", price: "Price", amount: "Amount", type: "Type", unit: "Unit", date: "Date", status: "Status", notes: "Notes", description: "Description", name: "Name", email: "Email", phone: "Phone", address: "Address", city: "City", store: "Store", allStores: "All stores", active: "Active", inactive: "Inactive", reason: "Reason", optional: "optional", required: "This field is required", noResults: "No results", showing: "{{from}}–{{to}} of {{total}}", page: "Page {{page}}", perPage: "per page", today: "Today", yesterday: "Yesterday", last7: "Last 7 days", last30: "Last 30 days", thisMonth: "This month", lastMonth: "Last month", custom: "Custom", from: "From", to: "To", apply: "Apply", vsPrevious: "vs previous period", estimate: "Estimate", language: "Language", theme: "Theme", light: "Light", dark: "Dark", system: "System", unknownError: "Something went wrong. Please try again.", permissionDenied: "You do not have permission to perform this action.", deleteConfirmTitle: "Confirm deletion", deleteConfirmText: "This action cannot be undone. Continue?", saved: "Saved successfully", deleted: "Deleted successfully", copied: "Copied", print: "Print", download: "Download", refresh: "Refresh", viewAll: "View all", more: "More", less: "Less", select: "Select", change: "Change", remove: "Remove", columns: "Columns",
  },
  nav: { dashboard: "Dashboard", pos: "POS", products: "Products", inventory: "Inventory", sales: "Sales", purchases: "Purchases", suppliers: "Suppliers", customers: "Customers", expenses: "Expenses", analytics: "Analytics", ai: "AI Assistant", employees: "Employees", stores: "Stores", settings: "Settings", register: "Cash register", planner: "New store planner", notifications: "Notifications", audit: "Audit log", logout: "Log out", profile: "My profile" },
  auth: {
    signIn: "Sign in", signUp: "Create account", signOut: "Sign out", email: "Email address", password: "Password", confirmPassword: "Confirm password", newPassword: "New password", currentPassword: "Current password", firstName: "First name", lastName: "Last name", forgotPassword: "Forgot password?", resetPassword: "Reset password", sendResetLink: "Send reset link", resetSent: "If an account exists for this email, a reset link has been sent.", resetSentDev: "Email sending is not configured. In development the link is printed in the server console.", resetDone: "Your password has been reset. You can now sign in.", invalidToken: "This link is invalid or has expired.", noAccount: "Don't have an account?", haveAccount: "Already have an account?", invalidCredentials: "Incorrect email or password.", accountInactive: "This account is disabled. Contact the owner.", rateLimited: "Too many attempts. Try again in a few minutes.", passwordRules: "At least 8 characters with a letter and a number.", passwordsMismatch: "Passwords do not match.", welcomeBack: "Welcome back", signInSubtitle: "Sign in to your management workspace", signUpSubtitle: "Create your owner account — you'll set up your business next.", emailExists: "An account already exists with this email.", accountCreated: "Account created. Signing in…", changePassword: "Change password", passwordChanged: "Password changed.",
  },
  onboarding: {
    title: "Let's set up your business", subtitle: "A few details to get started. You can change everything later.", step1: "Your business", step2: "Contact details", step3: "First store", businessName: "Business name", businessType: "Business type", ownerName: "Owner name", taxRate: "Default VAT", currency: "Currency", storeName: "Store name", storeNameHint: "E.g. Maarif Shop, Main store…", finish: "Finish setup",
    types: { MINI_MARKET: "Mini market", GROCERY: "Grocery", CLOTHING: "Clothing", ELECTRONICS: "Electronics", COSMETICS: "Cosmetics", RESTAURANT: "Restaurant / Snack", COFFEE_SHOP: "Coffee shop / Café", PHARMACY: "Parapharmacy", OTHER: "Other" },
  },
  dashboard: { title: "Dashboard", revenue: "Revenue", grossProfit: "Gross profit", netProfit: "Net profit", transactions: "Transactions", aov: "Average order", expenses: "Expenses", inventoryValue: "Inventory value (cost)", lowStock: "Low stock", outOfStock: "Out of stock", topProducts: "Top-selling products", salesTrend: "Sales trend", paymentMethods: "Payment methods", recentSales: "Recent sales", lowStockProducts: "Products to reorder", noLowStock: "No low-stock products", noSales: "No sales in this period", grossMargin: "Gross margin", netMargin: "Net margin", cogs: "Cost of goods sold", refunds: "Refunds", profit: "Profit", openRegister: "Open register", goToPos: "Go to POS", registerOpen: "Register open", registerClosed: "Register closed" },
  pos: {
    title: "Point of sale", scanOrSearch: "Scan a barcode or search…", cart: "Cart", emptyCart: "Cart is empty", emptyCartHint: "Scan a product or use the search", customer: "Customer", walkIn: "Walk-in customer", selectCustomer: "Select customer", hold: "Hold", resume: "Resume", heldCarts: "Held carts", noHeldCarts: "No held carts", clear: "Clear", pay: "Charge", payment: "Payment", paymentMethod: "Payment method", splitPayment: "Split payment", addPayment: "Add payment", received: "Received", remaining: "Remaining", change: "Change due", complete: "Complete sale", completing: "Completing…", saleComplete: "Sale recorded", receipt: "Receipt", printReceipt: "Print receipt", printThermal: "Thermal printer", newSale: "New sale", orderDiscount: "Order discount", lineDiscount: "Line discount", unitPrice: "Unit price", stock: "Stock: {{count}}", insufficientStock: "Insufficient stock for {{name}} (available: {{available}})", registerRequired: "Open the register to accept cash", registerClosed: "No open register", openRegister: "Open register", productNotFound: "No product found for “{{term}}”",
    methods: { CASH: "Cash", CARD: "Card / TPE", BANK_TRANSFER: "Bank transfer", CHECK: "Check", OTHER: "Other", CREDIT: "Credit" },
    creditFor: "Credit for {{name}}", creditDue: "Balance due (credit)", creditNeedsCustomer: "Select a customer to sell on credit", creditNoLimit: "{{name}} has no credit limit (set one on their profile)", creditNotAllowed: "You are not allowed to sell on credit",
    reference: "Reference (transaction no.…)", cashier: "Cashier", thankYou: "Thank you for your visit!", items: "{{count}} item(s)", quickAmounts: "Quick amounts", exact: "Exact amount", categories: "Categories", allCategories: "All", keyboardHint: "Enter: add · F2: pay · F4: hold",
  },
  register: {
    title: "Cash register", open: "Open register", close: "Close register", openingBalance: "Opening cash float", registerName: "Register name", openedBy: "Opened by", openedAt: "Opened at", closedAt: "Closed at", cashSales: "Cash sales", cashRefunds: "Cash refunds", deposits: "Deposits", withdrawals: "Withdrawals", customerPayments: "Customer repayments (credit)", expected: "Expected cash", actual: "Counted cash", difference: "Difference", differenceReason: "Reason for difference", differenceReasonRequired: "A reason is required when there is a difference", deposit: "Deposit", withdrawal: "Withdrawal", addTransaction: "Cash movement", transactions: "Movements", noOpen: "No open register for this store", history: "Register history", summary: "Session summary", salesCount: "Number of sales", closeConfirm: "Are you sure you want to close the register?", closed: "Register closed", opened: "Register opened",
    status: { OPEN: "Open", CLOSED: "Closed" }, types: { SALE: "Sale", REFUND: "Refund", DEPOSIT: "Deposit", WITHDRAWAL: "Withdrawal", ADJUSTMENT: "Adjustment", CUSTOMER_PAYMENT: "Customer repayment" },
  },
  products: {
    title: "Products", add: "Add product", edit: "Edit product", sku: "SKU", barcode: "Barcode", category: "Category", brand: "Brand", supplier: "Supplier", purchasePrice: "Purchase price (excl. tax)", sellingPrice: "Selling price (incl. tax)", costPrice: "Average cost", margin: "Margin", stock: "Stock", minStock: "Minimum stock", maxStock: "Maximum stock", unit: "Unit", taxRate: "VAT", image: "Image (URL)", initialStock: "Initial stock", lowStockOnly: "Low stock only", bulkPrice: "Bulk price update", bulkStock: "Bulk stock update", importCsv: "Import CSV", exportCsv: "Export CSV", importHint: "Columns: name, sku, barcode, category, brand, purchasePrice, sellingPrice, taxRate, stockQuantity, minimumStock, unit", importResult: "{{created}} created, {{updated}} updated, {{errors}} error(s)", downloadTemplate: "Download template", selected: "{{count}} selected",
    priceMode: { SET: "Set to", PERCENT: "Adjust by %", AMOUNT: "Adjust by (DH)" }, field: { sellingPrice: "Selling price", purchasePrice: "Purchase price" },
    deleteConfirm: "Delete this product? It will be archived and hidden from the POS.", duplicateBarcode: "This barcode is already used in this store", duplicateSku: "This SKU is already used in this store", categories: "Categories", brands: "Brands", manageCategories: "Manage categories", newCategory: "New category", newBrand: "New brand", parentCategory: "Parent category", productsCount: "{{count}} product(s)", noProducts: "No products", noProductsHint: "Add your first product or import a CSV file.", generateSku: "Generate",
  },
  inventory: {
    title: "Inventory", movements: "Stock movements", adjust: "Adjust stock", transfer: "Transfer", summary: "Summary", costValue: "Value (cost)", retailValue: "Value (retail)", totalUnits: "Units in stock", type: "Type", previous: "Before", change: "Change", newQty: "After", user: "User", product: "Product", adjustType: "Adjustment type", newQuantity: "New quantity", qty: "Quantity", fromStore: "Source store", toStore: "Destination store", reorder: "Reorder recommendations", reorderHint: "Estimates based on sales velocity over the last {{days}} days. These are not guaranteed forecasts.", avgDaily: "Sales / day", daysLeft: "Days left", suggested: "Suggested qty", estCost: "Est. cost",
    urgency: { OUT: "Out", CRITICAL: "Critical", LOW: "Low", OK: "OK" }, createPo: "Create purchase order",
    types: { SALE: "Sale", PURCHASE: "Purchase", RETURN: "Return", ADJUSTMENT: "Adjustment", TRANSFER: "Transfer", DAMAGE: "Damage", LOSS: "Loss" }, noMovements: "No movements", adjusted: "Stock adjusted", transferred: "Transfer completed",
  },
  sales: {
    title: "Sales", number: "Sale no.", items: "Items", payment: "Payment", cashier: "Cashier", refund: "Refund", cancel: "Cancel sale", refundTitle: "Refund", refundQty: "Qty to refund", refundAmount: "Refund amount", restock: "Return to stock", refundMethod: "Refund method", refunded: "Refund completed", cancelled: "Sale cancelled", cancelReason: "Cancellation reason", cancelHint: "Only possible while the sale's register is open. Otherwise use a refund.", refunds: "Refunds",
    status: { COMPLETED: "Completed", CANCELLED: "Cancelled", REFUNDED: "Refunded", PARTIALLY_REFUNDED: "Partially refunded", DRAFT: "Draft" }, noSales: "No sales", viewReceipt: "View receipt",
    paymentStatus: { PAID: "Paid", PENDING: "On credit (unpaid)", PARTIALLY_PAID: "Partially paid", REFUNDED: "Refunded" },
    refundCreditHint: "{{amount}} MAD is still owed on credit for this sale: choose “Credit” to cancel that debt instead of returning money.",
  },
  purchases: {
    title: "Purchases", orders: "Purchase orders", create: "New order", edit: "Edit order", number: "Order no.", supplier: "Supplier", expected: "Expected delivery", delivered: "Delivered on", receive: "Receive", receiveTitle: "Receive goods", ordered: "Ordered", received: "Received", receiving: "To receive", receiveAll: "Receive all", updatePrice: "Update product purchase prices", markOrdered: "Mark as ordered", saveDraft: "Save as draft", cancelOrder: "Cancel order", addProduct: "Add product", unitPriceHT: "Unit price (excl. tax)",
    status: { DRAFT: "Draft", ORDERED: "Ordered", PARTIALLY_RECEIVED: "Partially received", RECEIVED: "Received", CANCELLED: "Cancelled" }, noOrders: "No orders", receivedOk: "Receipt recorded, stock updated",
  },
  suppliers: { title: "Suppliers", add: "Add supplier", edit: "Edit supplier", taxNumber: "Tax ID (ICE)", creditLimit: "Credit limit", balance: "Balance due", pay: "Record payment", paid: "Payment recorded", performance: "Performance", orderCount: "Orders", totalPurchases: "Total purchases", avgDelivery: "Avg. delivery (days)", onTime: "On-time deliveries", products: "Supplied products", history: "Order history", noSuppliers: "No suppliers" },
  customers: {
    title: "Customers", add: "Add customer", edit: "Edit customer", loyalty: "Loyalty points", totalSpending: "Total spent", balance: "Balance due", orders: "Orders", avgOrder: "Average order", lastPurchase: "Last purchase", history: "Purchase history", noCustomers: "No customers",
    credit: "Credit (tab)", creditLimit: "Credit limit", creditLimitHint: "Leave empty to disallow credit sales for this customer.", creditAvailable: "Credit available", noCredit: "No credit", owes: "Owes", settled: "settled",
    recordPayment: "Record repayment", paymentRecorded: "Repayment recorded. New balance: {{balance}} MAD", paymentHistory: "Repayments received", cashPaymentHint: "Cash repayments are added to the open register.", receivablesSummary: "{{count}} customer(s) owe a total of {{total}} MAD",
  },
  expenses: {
    title: "Expenses", add: "Add expense", edit: "Edit expense", category: "Category", paymentMethod: "Payment method", totalPeriod: "Total for period", categories: "Expense categories", newCategory: "New category", cashHint: "Cash expenses are deducted from the open register.", noExpenses: "No expenses",
    codes: { RENT: "Rent", ELECTRICITY: "Electricity", INTERNET: "Internet", SALARIES: "Salaries", TRANSPORT: "Transport", MARKETING: "Marketing", MAINTENANCE: "Maintenance", SUPPLIES: "Supplies", OTHER: "Other" },
  },
  analytics: {
    title: "Analytics", pnl: "Profit & loss", sales: "Sales", inventory: "Inventory", customers: "Customers", suppliers: "Suppliers", payments: "Payments", revenue: "Revenue (incl. tax)", netRevenue: "Net revenue (excl. tax)", cogs: "Cost of goods sold", grossProfit: "Gross profit", grossMargin: "Gross margin", totalExpenses: "Total expenses", netProfit: "Net profit", netMargin: "Net margin", tax: "VAT collected", refunds: "Refunds", groupBy: "Group by",
    groups: { day: "Day", hour: "Hour", cashier: "Cashier", category: "Category", store: "Store" }, turnover: "Inventory turnover (annualised)", turnoverHint: "COGS ÷ ending inventory value, annualised. Approximation based on end-of-period stock.", potentialProfit: "Potential profit in stock", byCategory: "By category", topCustomers: "Top customers", anonymous: "Sales without customer", newCustomers: "New customers", share: "Share", count: "Count", formulas: "Formulas", formulaText: "Gross profit = Net revenue − COGS · Net profit = Gross profit − Expenses · Margin = Profit ÷ Net revenue",
    export: "Export", exportPdf: "Download as PDF", exportCsv: "Download as CSV (Excel)", exporting: "Generating…", salesReport: "Sales report", inventoryReport: "Inventory report", customerReport: "Customer report", topProducts: "Top products", paymentMethods: "Payment methods", receivables: "Customer receivables (credit)", generatedAt: "Generated on", page: "Page",
    revenueSection: "Revenue", grossRevenue: "Gross revenue (incl. tax)", taxCollected: "Tax collected", netRevenueHT: "Net revenue (excl. tax)", expensesSection: "Expenses", resultSection: "Result", transactions: "Transactions", averageOrder: "Average order",
    pnlNote: "Credit sales are recognised as revenue on the sale date (accrual basis). Outstanding customer balances are listed in the Receivables report.",
    units: "Units", stockValuation: "Stock valuation", productCount: "Number of products", totalUnits: "Units in stock", costValue: "Value at cost", retailValue: "Value at retail", cogsInPeriod: "COGS in period", anonymousSales: "Sales without identified customer", debtors: "Debtor customers", totalReceivables: "Total receivables",
  },
  ai: {
    title: "AI Assistant", subtitle: "Ask in French, Arabic, Darija or English. Answers are computed from your real data.", placeholder: "E.g. Which product earns me the most this month?", ask: "Ask", examples: "Examples", ex1: "What product sells the most this week?", ex2: "Which products are running low?", ex3: "Why did my profits decrease this month?", ex4: "What should I order from suppliers?", ex5: "Sales summary for this month", ex6: "شنو أكثر produit تباع هاد السيمانة؟",
    source: { llm: "AI-generated answer from your data", template: "Answer computed from your data" }, llmNotConfigured: "No AI API key configured: answers are produced by deterministic calculations. Add OPENAI_API_KEY for natural-language answers.", llmDegraded: "The AI service is configured but unavailable ({{reason}}): answers are produced by deterministic calculations from your data.", period: "Period analysed", showData: "Show data", thinking: "Analysing…",
  },
  planner: {
    title: "New store planner", subtitle: "Get a planning proposal from your budget. All values are estimates.", budget: "Total budget (DH)", businessType: "Business type", size: "Floor area (m²)", customers: "Expected customers / day", rent: "Monthly rent (DH, optional)", employees: "Employees", generate: "Generate proposal", allocation: "Budget allocation", equipment: "Equipment", essential: "Essential", optional: "Optional", categories: "Categories & initial stock", recurring: "Estimated monthly costs", projection: "Projection", monthlyRevenue: "Est. monthly revenue (incl. tax)", monthlyGross: "Monthly gross profit", monthlyNet: "Monthly net profit", breakEven: "Break-even (net revenue / month)", breakEvenCustomers: "Customers / day needed", payback: "Payback period", months: "{{count}} months", notProfitable: "Not profitable with these assumptions", assumptions: "Assumptions", formulas: "Formulas used", disclaimer: "These estimates rely on averages and do not guarantee any financial outcome.", inventoryBudget: "Initial inventory budget", workingCapital: "Cash reserve", deposit: "Deposit (2 months)", firstRent: "First month rent",
  },
  notifications: { title: "Notifications", markAllRead: "Mark all as read", empty: "No notifications", unread: "{{count}} unread", types: { LOW_STOCK: "Low stock", OUT_OF_STOCK: "Out of stock", LARGE_EXPENSE: "Large expense", SALES_DECREASE: "Sales decrease", REGISTER_DISCREPANCY: "Register discrepancy", PURCHASE_RECEIVED: "Order received", SYSTEM: "System" } },
  employees: {
    title: "Employees", add: "Add employee", edit: "Edit employee", role: "Role", stores: "Stores", lastLogin: "Last login", never: "Never", resetPassword: "New password (optional)",
    roles: { OWNER: "Owner", ADMIN: "Administrator", MANAGER: "Manager", CASHIER: "Cashier", INVENTORY_MANAGER: "Inventory manager", ACCOUNTANT: "Accountant" },
    roleHints: { OWNER: "Full access including billing and deletion.", ADMIN: "Full operational access except critical settings.", MANAGER: "Sales, inventory, purchases, reports.", CASHIER: "Sales and register only.", INVENTORY_MANAGER: "Products, stock, purchases.", ACCOUNTANT: "Reports, expenses, audit (read)." },
    statuses: { ACTIVE: "Active", INACTIVE: "Inactive", SUSPENDED: "Suspended" }, deleteConfirm: "Delete this employee? Their history will be kept.",
  },
  stores: { title: "Stores", add: "Add store", edit: "Edit store", size: "Floor area (m²)", openTime: "Opens", closeTime: "Closes", products: "Products", users: "Users", deleteHint: "A store can only be deleted when it has no stock and no open register.", current: "Current store" },
  settings: {
    title: "Settings", business: "Business", profile: "Profile", security: "Security", appearance: "Appearance", logo: "Logo (URL)", plan: "Subscription", audit: "Audit log", auditEmpty: "No entries", action: "Action", entity: "Entity", when: "When", who: "Who", ip: "IP",
    integrations: "Integrations", integrationsHint: "Keys are read from the server environment (.env). They are never displayed or sent to the browser.", configured: "Configured", notConfigured: "Not configured", active: "Active", fallback: "Memory fallback", database: "Database",
    aiIntegration: "AI assistant (OpenAI)", aiHelp: "Set OPENAI_API_KEY (and OPENAI_MODEL) for natural-language answers. Without a key the assistant answers with deterministic templates.",
    emailIntegration: "E-mail (SMTP)", emailHelp: "Set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD and SMTP_FROM for password resets and alerts.",
    redisIntegration: "Redis (shared rate limiting)", redisHelp: "Set REDIS_URL to share rate limiting across several instances. Without Redis an in-memory limiter is used.",
    cronIntegration: "Daily job (cron)", cronHelp: "Call POST /api/cron/daily with header Authorization: Bearer CRON_SECRET once a day.",
    whatsappIntegration: "WhatsApp", whatsappHelp: "Not implemented. Architecture ready for a provider (e.g. WhatsApp Business API).",
    sendTestEmail: "Send test e-mail", testEmailSent: "Test e-mail sent to {{to}}", model: "Model", lastError: "Last error",
  },
  errors: { VALIDATION_ERROR: "Invalid data", UNAUTHORIZED: "Session expired, please sign in again", FORBIDDEN: "Action not allowed", NOT_FOUND: "Item not found", CONFLICT: "Conflicts with existing data", INSUFFICIENT_STOCK: "Insufficient stock", REGISTER_CLOSED: "The register is closed", REGISTER_ALREADY_OPEN: "A register is already open", PAYMENT_MISMATCH: "Payments do not match the total", CREDIT_NOT_ALLOWED: "This customer has no credit limit. Set one on their profile first.", CREDIT_LIMIT_EXCEEDED: "Credit limit exceeded", REFUND_EXCEEDS_CREDIT: "Amount exceeds the credit still owed on this sale", NO_OUTSTANDING_BALANCE: "This customer has no outstanding balance", INVALID_STATE: "Operation not possible in the current state", RATE_LIMITED: "Too many requests, please wait", INTERNAL_ERROR: "Server error, please try again", NETWORK: "Cannot connect. Check your network." },
  pwa: { install: "Install app", offline: "You are offline. Some features are unavailable." },
  offline: {
    title: "Offline sales", description: "Sales taken without a connection are stored on this device and sent to the server automatically when the network returns. A sale the server rejects stays here until the cause is fixed.",
    offline: "Offline", online: "Connected", queued: "{{count}} pending", empty: "No pending sales", status: { pending: "Pending", failed: "Rejected" },
    retry: "Retry", discard: "Delete", discardTitle: "Delete this offline sale?", discardText: "Sale {{ref}} will be permanently removed from this device and never sent to the server. Stock will not be deducted.",
    syncNow: "Sync now", syncedCount: "{{count}} sale(s) synced", failedCount: "{{count}} sale(s) rejected by the server",
    saleQueued: "Offline: sale {{ref}} saved on this device, it will sync when the network is back", provisionalReceipt: "PROVISIONAL RECEIPT — OFFLINE",
    fixThenRetry: "fix the cause, then retry", creditNotOffline: "Credit sales need a connection (limit check).", servedFromCache: "Showing data from the local cache", pendingBanner: "{{count}} offline sale(s) waiting to sync",
  },
} satisfies Translation

export default en
